name: movies_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  google_fonts: ^5.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
   - family: Roboto
   - fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400